#! /bin/bash

ROOT_DIR=$PWD
PLANTUML_FILE=$ROOT_DIR/plantuml.jar
JAVA_EXEC=java
COMMANDS=-verbose
JAVA_EXEC_COMMAND=-jar
UML_INPUT_FILE=$1

$JAVA_EXEC $JAVA_EXEC_COMMAND $PLANTUML_FILE $COMMANDS $UML_INPUT_FILE
